# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    timeout-minutes: 40
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '1.9'
      - name: Run the install
        run: |
          meteor npm install
      - name: install mock server
        run: |
          cd tests/mockServer && npm install && cd ../../
      - name: start the mock server
        run: |
          node tests/mockServer/index.js &
      - name: start meteor app
        run: |
          meteor --settings ./settings-files/E2E-test.json &
      - name: Sleep for 7 min
        uses: jakejarvis/wait-action@master
        with:
          time: '420s'
      - name: Cypress run
        run: |
          npm run cypress:headless
      - name: Test docker image building
        run: |
          docker build .